debug: true

server:
  port: 8888

zuul:
  routes:
    geo-service:
      path: /geo/**
      url: http://localhost:9090

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

spring:
  datasource:
     url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
     platform: h2
     username: sa
     password:
     driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false


security:
  oauth2:
    resource:
      filter-order: 3
